### ISSUE TITLE
PRÁCTICA_MAYRA

### ISSUE THREAD

**Issue by mayraglez917** [SistemasTecTlaxiaco/practica-de-operaciones-basicas-mayraglez917#2]
[EJERCICIOS_MAYRA_GLEZ.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-operaciones-basicas-mayraglez917/files/12566796/EJERCICIOS_MAYRA_GLEZ.pdf)

**Comment by 23620031** [comment]
PORTADA 25/25
PROCEDIMIENTO 25/25
FIGURAS ILUSTRACIONES Y FOTOGRAFÍAS 25/25
RESULTADOS Y CONCLUSIONES 25/25

CALIFICACIÓN 20/20

CALIFICADO POR EQUIPO DE "LÓPEZ DOMÍNGUEZ ISAÍAS BRAYAN"

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
